[BEAM-10260] Fix continuation token support with statecache
The continuation mode was always-on by mistake. Also, continuation mode would
arbitrarily nest appended state via iterators which would lead to the following
error:

```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

In case of continuations tokens, we do not cache anything anymore after the
continuation. Caching after the continuation token would defeat the purpose of
using continuation tokens for large state. A test was added for continuation
tokens.

The extend operation was removed from the statecache in favor of using only
put/get/clear which avoids any race conditions with the cache eviction.

[BEAM-10260] Remove is_cached parameter from CachingStateHandler

The parameter is not needed anymore because side input caching has been
implemented, which was the original reason for having the parameter.